nombre = input("¿cual es tu nombre? ")
apellido = input("¿cual es tu apellido? ")
seccion = input("¿cual es tu seccion? ")
sede = input("¿cual es tu sede? ")
print("Hola soy " + nombre, apellido + " estoy en la seccion "+ seccion +" en la sede " + sede)